apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: py-mcp-server-go-ecommerce-route
  namespace: test-a
  labels:
    app: py-mcp-server-go-ecommerce-route
spec:
  hostnames:
    - "py-mcp-server-go-ecommerce.architecturedev.caradhras.io"
  parentRefs:
    - name: alb-arch-eks-002-gateway
      namespace: test-a
      sectionName: http-listener
    - name: alb-arch-eks-002-gateway
      namespace: test-a
      sectionName: https-listener
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: svc-py-mcp-server-go-ecommerce
          port: 9002
