apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name py-mcp-server-go-ecommerce-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.0.0"
  ACCOUNT: "aws:992382474575"
  APP_NAME: "py-mcp-server-go-ecommerce"
  HOST: "0.0.0.0"
  PORT: "9002"
  SESSION_TIMEOUT: "700"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-02-otel-collector.default.svc.cluster.local:4317"
  INVENTORY_URL: "https://go-inventory.architecture.caradhras.io"
  ORDER_URL: "https://go-order.architecture.caradhras.io"
  
  LOG_LEVEL: "warning" #info, error, warning
