apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-py-mcp-server-ecommerce
  namespace: test-a
spec:
  minAvailable: 1
  selector:
    matchLabels:
        app: py-mcp-server-ecommerce