apiVersion: v1
kind: Service
metadata:
  name: &app-name svc-py-mcp-server-ecommerce
  namespace: test-a
  labels:
    app: *app-name
spec:
  type: ClusterIP
  ports:
  - port: 9002
    targetPort: 9002
    protocol: TCP
    name: http
  selector:
    app: go-py-mcp-server-ecommerce
